name: PublishDocker_vsc_vnc
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: subinghong/ubuntu-ssh
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dockerfile_ubuntu_sshd_tailscale
        tags: "vsc_vnc_$CI_SHA_SHORT"
