name: PublishDocker_vsc_vnc
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: pre-step
      shell: bash
      run: |
        echo "CI_SHA_SHORT=${CI_SHA_SHORT}"
        echo "release-version=$(echo ${CI_SHA_SHORT:1})" >> $GITHUB_OUTPUT
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: subinghong/ubuntu-ssh
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dockerfile_ubuntu_sshd_tailscale
        tags: "${{ steps.pre-step.outputs.release-version }}"
        cache: true
